-- This script must be executed in the same order as it appears here

DROP TABLE IF EXIST MOVIES;
DROP TABLE IF EXISTS SHOW_TIMES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS REVIEW_RATINGS;

CREATE TABLE MOVIES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL,
    DESCRIPTION VARCHAR(255),
    RELEASED_DATE VARCHAR(255) NOT NULL,
    IMDB_RATING VARCHAR(255) NOT NULL,
    RUNTIME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE SHOW_TIMES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ID_MOVIE INTEGER NOT NULL,
    SHOW_TIME DATETIME NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_MOVIE_ID FOREIGN KEY(ID_MOVIE) REFERENCES MOVIES (ID)
);

CREATE TABLE USERS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    LASTNAME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE REVIEW_RATINGS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ID_MOVIE INTEGER NOT NULL,
    ID_USER INTEGER NOT NULL,
    RATING VARCHAR(1) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_RR_MOVIE_ID FOREIGN KEY(ID_MOVIE) REFERENCES MOVIES (ID),
    CONSTRAINT FK_RR_USER_ID FOREIGN KEY(ID_USER) REFERENCES USERS (ID),
    CONSTRAINT UK_RR_MOVIE_USER UNIQUE (ID_MOVIE, ID_USER)
);

